steps:
- name: node:18.13.0
  entrypoint: npm
  args: ["install"]
- name: node:18.13.0
  entrypoint: npm
  args: ["start", "create-env"]
  env:
    - 'SECRET_KEY=${_SECRET_KEY}'
    - 'DB_CLIENT=${_DB_CLIENT}' 
    - 'DB_HOST=${_DB_HOST}'
    - 'DB_USER=${_DB_USER}'
    - 'DB_PASS=${_DB_PASS}'
    - 'DB_NAME=${_DB_NAME}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"